
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'insurance_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  
    insurance_model:
      +materialized: incremental
      +file: customers_model.sql
      # dbt_project.yml

    
    table:
      incident:
        incident:
      +enabled: true
      +materialized: table
      insurance_company:
        +enabled: true
        +materialized: table
      department:
        +enabled: true
        +materialized: table
      vehicle_service:
        +enabled: true
        +materialized: table
      vehicle:
        +enabled: true
        +materialized: table
      premium_payments:
        +enabled: true
        +materialized: table
      application:
        +enabled: true
        +materialized: table
      insurance_policy:
        +enabled: true
        +materialized: table
      incident_report:
        +enabled: true
        +materialized: table
      claim:
        +enabled: true
        +materialized: table
      


# dbt_project.yml



# Seeds section
seeds:


  insurance_project:  # Replace with your project name
    dbt_sravyats94:   # Schema where the seed will be created
      +schema: analytics  # Define the schema where seeds will be loaded
      +quote_columns: true  # Ensure columns are quoted
      +database: Analytics  # Define the database
      customers:  # Define the seed file, without the '.csv' extension
        +enabled: true  # Enable the seed
        +column_types:  # Define column types
          Cust_Id: varchar(20)
          Cust_FName: varchar(10)
          Cust_LName: varchar(10)
          Cust_DOB: date
          Cust_Gender: char(2)
          Cust_Address: varchar(20)
          Cust_MOB_Number: integer
          Cust_Email: varchar(20)
          Cust_Passport_Number: varchar(20)
          Cust_Marital_Status: char(8)
          Created_dtm: timestamp
          Updated_dtm: timestamp
      incident:
        +enabled: true
        +column_types:
          Incident_Id: VARCHAR(20)
          Incident_Type: VARCHAR(30)
          Incident_Date: DATE
      insurance_company:
        column_types:
           Company_Name: VARCHAR(20)
           Company_Address: VARCHAR(20) 
           Company_Contact_Number: INTEGER 
           Company_Fax: INTEGER
           Company_Email: VARCHAR(20) 
           Company_Website: VARCHAR(20)
           Company_Location: VARCHAR(20)
           Company_Department_Name: VARCHAR(20) 
           Company_Office_Name: VARCHAR(20)
      department:
        column_types:
            Department_Name: VARCHAR(20)
            Department_ID: VARCHAR(20)
            Department_Staff: CHAR(18) 
            Department_Offices: CHAR(18) 
            Company_Name: VARCHAR(20)
      vehicle_service:
        column_types:
              Department_Name: VARCHAR(20) 
              Vehicle_Service_Company_Name: VARCHAR(20)
              Vehicle_Service_Address: VARCHAR(20)
              Vehicle_Service_Contact: VARCHAR(20) 
              Vehicle_Service_Incharge: VARCHAR(20) 
              Vehicle_Service_Type: VARCHAR(20)
              Department_Id: VARCHAR(20) 
              Company_Name: VARCHAR(20)
      vehicle:
        column_types:
               Vehicle_Id: VARCHAR(20) 
               Policy_Id: VARCHAR(20) 
               Dependent_NOK_Id: VARCHAR(20)
               Vehicle_Registration_Number: VARCHAR(20)
               Vehicle_Value: INTEGER
               Vehicle_Type: VARCHAR(20) 
               Vehicle_Size: INTEGER
               Vehicle_Number_Of_Seat: INTEGER
               Vehicle_Manufacturer: VARCHAR(20)
               Vehicle_Engine_Number: INTEGER 
               Vehicle_Chasis_Number: INTEGER
               Vehicle_Number: VARCHAR(20) 
               Vehicle_Model_Number: VARCHAR(20) 
               Cust_Id: VARCHAR(20)
      premium_payment:
        column_types:
  
              Premium_Payment_Id: VARCHAR(20)
              Policy_Number: VARCHAR(20)
              Premium_Payment_Amount: INTEGER 
              Premium_Payment_Schedule: DATE
              Receipt_Id: VARCHAR(20)
              Cust_Id: VARCHAR(20)

      application:
        column_types:
              Application_Id: VARCHAR(20) 
              Vehicle_Id: VARCHAR(20)
              Application_Status: CHAR(8) 
              Coverage: VARCHAR(50)
              Cust_Id: VARCHAR(20) 
      insurance_policy:
        column_types:
              Agreement_id: VARCHAR(20) 
              Department_Name: VARCHAR(20) 
              Policy_Number: VARCHAR(20) 
              Start_Date: DATE
              Expiry_Date: DATE 
              Term_Condition_Description: VARCHAR(100) 
              Application_Id: VARCHAR(20)
              Cust_Id: VARCHAR(20) 
        claim:     
          column_types:
              Claim_Id: VARCHAR(20)
              Agreement_Id: VARCHAR(20) 
              Claim_Amount: INTEGER
              Incident_Id: VARCHAR(20) 
              Damage_Type: VARCHAR(20)
              Date_Of_Claim: DATE
              Claim_Status: CHAR(10)
              Cust_Id: VARCHAR(20)




 


